services:
  _defaults:
    public: true

  fruit.grid.data.factory.fruits_data_factory:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@fruit.grid.query.fruits_query_builder'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'fruits'
